data-path = data/esol.csv
output-dir = esol_ckpts
task-type = regression
metrics = [rmse]
epochs = 60
split-sizes = [0.7, 0.1, 0.2]
num-workers = 0
batch-size = 64
accelerator = auto
devices = auto
rxn-mode = REAC_DIFF
multi-hot-atom-featurizer-mode = V2
frzn-ffn-layers = 0
ensemble-size = 1
message-hidden-dim = 300
depth = 3
dropout = 0.0
activation = RELU
aggregation = norm
aggregation-norm = 100
ffn-hidden-dim = 300
ffn-num-layers = 1
multiclass-num-classes = 3
v-kl = 0.0
eps = 1e-08
alpha = 0.1
tracking-metric = val_loss
warmup-epochs = 2
init-lr = 0.0001
max-lr = 0.001
final-lr = 0.0001
split = RANDOM
split-key-molecule = 0
num-replicates = 1
data-seed = 0
